#############################################################################
# Makefile for building: villie
# Generated by qmake (2.01a) (Qt 4.5.2) on: Sat Oct 24 03:06:52 2009
# Project:  villie.pro
# Template: app
# Command: d:\Apps\Dev\Qt\bin\qmake.exe -spec ../../Apps/Dev/Qt/mkspecs/win32-g++ -win32 -o Makefile villie.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = d:/Apps/Dev/Qt/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: villie.pro  ../../Apps/Dev/Qt/mkspecs/win32-g++/qmake.conf ../../Apps/Dev/Qt/mkspecs/qconfig.pri \
		../../Apps/Dev/Qt/mkspecs/features/qt_functions.prf \
		../../Apps/Dev/Qt/mkspecs/features/qt_config.prf \
		../../Apps/Dev/Qt/mkspecs/features/exclusive_builds.prf \
		../../Apps/Dev/Qt/mkspecs/features/default_pre.prf \
		../../Apps/Dev/Qt/mkspecs/features/win32/default_pre.prf \
		../../Apps/Dev/Qt/mkspecs/features/debug.prf \
		../../Apps/Dev/Qt/mkspecs/features/debug_and_release.prf \
		../../Apps/Dev/Qt/mkspecs/features/default_post.prf \
		../../Apps/Dev/Qt/mkspecs/features/win32/default_post.prf \
		../../Apps/Dev/Qt/mkspecs/features/win32/rtti.prf \
		../../Apps/Dev/Qt/mkspecs/features/win32/exceptions.prf \
		../../Apps/Dev/Qt/mkspecs/features/win32/stl.prf \
		../../Apps/Dev/Qt/mkspecs/features/shared.prf \
		../../Apps/Dev/Qt/mkspecs/features/warn_on.prf \
		../../Apps/Dev/Qt/mkspecs/features/qt.prf \
		../../Apps/Dev/Qt/mkspecs/features/win32/thread.prf \
		../../Apps/Dev/Qt/mkspecs/features/moc.prf \
		../../Apps/Dev/Qt/mkspecs/features/win32/windows.prf \
		../../Apps/Dev/Qt/mkspecs/features/resources.prf \
		../../Apps/Dev/Qt/mkspecs/features/uic.prf \
		../../Apps/Dev/Qt/mkspecs/features/yacc.prf \
		../../Apps/Dev/Qt/mkspecs/features/lex.prf \
		../../Apps/Dev/Qt/mkspecs/features/include_source_dir.prf \
		d:/Apps/Dev/Qt/lib/qtmaind.prl
	$(QMAKE) -spec ../../Apps/Dev/Qt/mkspecs/win32-g++ -win32 -o Makefile villie.pro
../../Apps/Dev/Qt/mkspecs/qconfig.pri:
../../Apps/Dev/Qt/mkspecs/features/qt_functions.prf:
../../Apps/Dev/Qt/mkspecs/features/qt_config.prf:
../../Apps/Dev/Qt/mkspecs/features/exclusive_builds.prf:
../../Apps/Dev/Qt/mkspecs/features/default_pre.prf:
../../Apps/Dev/Qt/mkspecs/features/win32/default_pre.prf:
../../Apps/Dev/Qt/mkspecs/features/debug.prf:
../../Apps/Dev/Qt/mkspecs/features/debug_and_release.prf:
../../Apps/Dev/Qt/mkspecs/features/default_post.prf:
../../Apps/Dev/Qt/mkspecs/features/win32/default_post.prf:
../../Apps/Dev/Qt/mkspecs/features/win32/rtti.prf:
../../Apps/Dev/Qt/mkspecs/features/win32/exceptions.prf:
../../Apps/Dev/Qt/mkspecs/features/win32/stl.prf:
../../Apps/Dev/Qt/mkspecs/features/shared.prf:
../../Apps/Dev/Qt/mkspecs/features/warn_on.prf:
../../Apps/Dev/Qt/mkspecs/features/qt.prf:
../../Apps/Dev/Qt/mkspecs/features/win32/thread.prf:
../../Apps/Dev/Qt/mkspecs/features/moc.prf:
../../Apps/Dev/Qt/mkspecs/features/win32/windows.prf:
../../Apps/Dev/Qt/mkspecs/features/resources.prf:
../../Apps/Dev/Qt/mkspecs/features/uic.prf:
../../Apps/Dev/Qt/mkspecs/features/yacc.prf:
../../Apps/Dev/Qt/mkspecs/features/lex.prf:
../../Apps/Dev/Qt/mkspecs/features/include_source_dir.prf:
d:\Apps\Dev\Qt\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../Apps/Dev/Qt/mkspecs/win32-g++ -win32 -o Makefile villie.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
